CREATE OR REPLACE PROCEDURE SCOTT.PRC_CALC_PROMEDIO
(P_N1 IN NUMBER, P_N2 IN NUMBER, P_N3 IN NUMBER, 
P_N4 IN NUMBER, P_NOTA_MENOR OUT NUMBER, 
P_PROMEDIO OUT NUMBER, P_CONDICON OUT VARCHAR2)
IS
 N_P_NOTA_MENOR NUMBER (2) := 0;
 N_P_PROMEDIO NUMBER (2,2) := 0;
 V_P_CONDICON VARCHAR2 (100):= NULL ;

BEGIN
 --NOTA MENOR
 IF (P_N1 < P_N2) AND (P_N1 < PN3) AND (P_N1 < P_N4) THEN
  N_P_NOTA_MENOR := P_N1;
 ELSIF
 IF (P_N2 < P_N1) AND (P_N2 < PN3) AND (P_N2 < P_N4) THEN
  N_P_NOTA_MENOR := P_N2;
  ELSIF
 IF (P_N3 < P_N1) AND (P_N3 < PN2) AND (P_N3 < P_N4) THEN
  N_P_NOTA_MENOR := P_N3;
 IF (P_N4 < P_N1) AND (P_N4 < PN2) AND (P_N4 < P_N3) THEN
  N_P_NOTA_MENOR := P_N4;
 END IF;
 
 --PROMEDIO
 N_P_PROMEDIO := ((P_N1 + P_N2 + P_N3 + P_N4 - N_P_NOTA_MENOR ) / 4);
 
 --CONDICION
  IF N_P_PROMEDIO > = 14 AND N_P_PROMEDIO <= 20 THEN
  V_P_CONDICON := 'APROBADO';
  ELSE 
  V_P_CONDICON := 'DESAPROBADO';    
  END IF; 
 
 --REPORTE
 DBMS_OUTPUT.PUT_LINE('NOTA MENOR:' || N_P_NOTA_MENOR);
 DBMS_OUTPUT.PUT_LINE('PROMEDIO :' || N_P_PROMEDIO);
 DBMS_OUTPUT.PUT_LINE('CONDICION :' || V_P_CONDICON);
END;