CREATE OR REPLACE PROCEDURE SCOTT.UPDATESALEMP2
(CODIGO EMP.EMPNO%TYPE, SALARIO EMP.SAL%TYPE)
IS  
  CONT NUMBER;
  EXCEP1 EXCEPTION;
BEGIN
  SELECT COUNT(1) INTO CONT
  FROM EMP
  WHERE EMPNO = CODIGO;
  IF(CONT= 0)THEN
    RAISE EXCEP1;
  END IF;
  UPDATE EMP
      SET SAL = SALARIO
      WHERE EMPNO = CODIGO;
  COMMIT;
  dbms_output.put_line( 'PROCESO OK');
EXCEPTION 
  WHEN EXCEP1 THEN
   dbms_output.put_line( 'CODIGO NO EXISTE');
END;

SET SERVEROUTPUT ON
CALL SCOTT.UPDATESALEMP2(9999,5000);