--7.3
CREATE OR REPLACE PROCEDURE UPDATESALEMP2
(CODIGO EMP.EMPNO%TYPE ,SALARIO EMP.SAL%TYPE)
IS 
  CONT NUMBER;
  EXCEP1 EXCEPTION;
BEGIN
  SELECT COUNT(*) INTO CONT
   FROM EMP
   WHERE EMPNO=CODIGO;
  IF(CONT=0)THEN
    RAISE EXCEP1;
  END IF;
  
  UPDATE EMP
    SET SAL=SALARIO
    WHERE EMPNO=CODIGO;
  COMMIT;
   DBMS_OUTPUT.PUT_LINE('PROCESO OK');
EXCEPTION
  WHEN EXCEP1 THEN
    DBMS_OUTPUT.PUT_LINE('CODIGO NO EXISTE');
END;

CALL UPDATESALEMP2(9999,5000);

--7.4
CREATE OR REPLACE PROCEDURE UPDATESALEMP3
(CODIGO EMP.EMPNO%TYPE ,SALARIO EMP.SAL%TYPE)
IS 
  CONT NUMBER;
BEGIN
  SELECT COUNT(*) INTO CONT
   FROM EMP
   WHERE EMPNO=CODIGO;
  IF(CONT=0)THEN
    RAISE_APPLICATION_ERROR(-20001,'NO EXISTE EMPLEADO');
  END IF;
  UPDATE EMP
    SET SAL=SALARIO
    WHERE EMPNO=CODIGO;
  COMMIT;
   DBMS_OUTPUT.PUT_LINE('PROCESO OK');
END;

CALL UPDATESALEMP3(9999,5000);
BEGIN UPDATESALEMP3(9999,5000);END;

--7.5
CREATE OR REPLACE PROCEDURE UPDATESALEMP4
(CODIGO EMP.EMPNO%TYPE ,SALARIO EMP.SAL%TYPE)
IS 
  CONT NUMBER;
BEGIN
  SELECT COUNT(*) INTO CONT
   FROM EMP
   WHERE EMPNO=CODIGO;
  IF(CONT=0)THEN
    RAISE_APPLICATION_ERROR(-20000,'NO EXISTE EMPLEADO');
  END IF;
  UPDATE EMP
    SET SAL=SALARIO
    WHERE EMPNO=CODIGO;
  COMMIT;
   DBMS_OUTPUT.PUT_LINE('PROCESO OK');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR NRO. ORA'|| to_char(sqlcode));
    DBMS_OUTPUT.PUT_LINE('ERROR NRO. ORA'|| to_char(sqlerrm));
END;


CALL UPDATESALEMP4(9999,5000);

