DECLARE
  CAD VARCHAR2(20);
BEGIN

  UPDATE EMP SET SAL = SAL + 100 WHERE EMPNO = 7369;
  CAD := CASE WHEN SQL%FOUND THEN 'TRUE' ELSE 'FALSE' END;
  DBMS_OUTPUT.put_line('FOUND: ' || CAD );

END;

SELECT * FROM EMP;


